name: Build and update Helm chart

on:
  push:
    tags:
      - 'dev-v*' 

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Get tag name
        id: vars
        run: echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Set lowercase owner
        run: echo "OWNER_LC=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log tag info
        run: "echo 'Building image for tag: $TAG'"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/kuber-app:${{ env.TAG }}
          context: .

  update-helm:
    runs-on: ubuntu-latest
    needs: build
    env:
      TAG: ${{ needs.build.outputs.tag }}
    steps:
      - name: Checkout Helm chart repository
        uses: actions/checkout@v4
        with:
          repository: viktoriadevv/helm-charts
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: my-chart

      - name: Update image tag in values.yaml
        working-directory: my-chart
        run: |
          echo "Updating image tag to $TAG"
          sed -i "s/^  tag: .*/  tag: ${TAG}/" values.yaml

      - name: Commit and push changes
        working-directory: my-chart
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add values.yaml
          git commit -m "Update image tag to ${TAG}"
          git push
